
DELIMITER //

CREATE TRIGGER UNIQUE_AUTH_NAME BEFORE INSERT ON AUTH FOR EACH ROW

BEGIN
    DECLARE MSG VARCHAR(256);
    CALL COUNT_AUTHS (NEW.NAME, @TOTAL);

    IF ((SELECT @TOTAL) > 0)
        SET MSG = CONCAT('UNIQUE RULE TRIGGER ERROR: IS NOT POSSIBLE SAVE THIS AUTH_NAME: ', NEW.NAME);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END;

// DELIMITER